name: ovn-kubernetes

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  # Run Sunday at midnight
  - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    timeout-minutes: 220
    strategy:
      fail-fast: false
    steps:
    - name: List packages
      run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
    - name: Check disk space
      run: df -h /
    - name: Free up disk space
      run: |
        sudo eatmydata apt-get remove --auto-remove -y \
          azure-cli aspnetcore-* dotnet-* ghc-* firefox \
          google-chrome-stable google-cloud-sdk \
          llvm-* microsoft-edge-stable mono-* msbuild php-* php7* \
          powershell temurin-8-jdk zulu-*
    - name: Check disk space 2
      run: df -h /
