name: Build and Test

on:
  push:
  pull_request:
  schedule:
    # Run Sunday at midnight
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build-ocp:
    runs-on: ubuntu-22.04
    steps:
    - name: install dependencies
      run: sudo apt install -y podman

    - name: Check out ovn-kubernetes
      uses: actions/checkout@v4
      with:
          path: src/github.com/openshift/ovn-kubernetes
          repository: openshift/ovn-kubernetes

    - name: Build OCP ovn-kubernetes container
      run: |
        podman build -t ovn-daemonset-f:ocp -f Dockerfile .
      working-directory: src/github.com/openshift/ovn-kubernetes
